version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This starts the local PostgreSQL DB
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432